### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Beheadedstraw**
Update example in readme to reflect example in code folder as this was eluding my non-caffeinated ass.

### CODE REVIEW

**Comment by Swarkin** [comment]
Could you clarify your changes?
I don't see a reason to create the AwaitableHTTPRequest Node inside of the script there as it is an export variable already.

**Comment by Beheadedstraw** [comment]
The export doesn't instantiate the variable, it only defines its type. The example in the readme will not work unless it's instantiated with .new(), which then needs to be added as a child to the current scene, unless I'm missing something here, the issue [here](https://github.com/Swarkin/Godot-AwaitableHTTPRequest/issues/4) is what helped me resolve it. 

[It also seems the code example that was in one of your commits never made it into the merge](https://github.com/Swarkin/Godot-AwaitableHTTPRequest/pull/5/commits/9495034f25c67f16cce64f8cf1b3f2f2b9918879#diff-edadae681c026dea5961cf2b47561968793d5febd32fea2a1ada0038d9305f77), looks like it was deleted and recreated? 

This edit brings it inline with the previous issue listed above.

**Comment by Swarkin** [comment]
Are export variables really this confusing? I'll see what I can do once I'm home.

I'll probably change the example to extend the AwaitableHTTPRequest Node instead, and add that approach to the examples scene.

**Comment by Swarkin** [comment]
Is this better?

**Comment by Beheadedstraw** [comment]
This looks fine, but wouldn't you still need to add it as a child to the scene to use it? I'll admit I'm new to godot/gdscript but that seems to be the point of contention is instantiating and adding it to the scene as a child to be able to use it, I'm still reading up on how godot does it's inheritance in scenes so this is probably just ignorance on my part. 

Also as a QoL thing I changed the order of the arguments in the `async_request` function since some/most people would be using POST instead of URL encoding everything in a GET and rarely set custom headers.

```gdscript
async_request(url: String, method := HTTPClient.Method.METHOD_GET, body := "", custom_headers := PackedStringArray()) -> HTTPResult:
```
Thanks for the great resource btw.

**Comment by Swarkin** [comment]
The order matches with Godot's HTTPRequest node, as seen in #3 to avoid confusion with people that used it before.

**Comment by Beheadedstraw** [comment]
Makes sense, no worries.

**Pull request merged**
